"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { selectedPollTotal, sensitivityPool, sensitivityAverages, syntheticThresholdSeats, readSyntheticShare, writeSensitivityView, type Weighting } from "@/lib/sensitivity";
import type { Party, Poll, PollsConfig } from "@/lib/types";
import { mediumDate } from "@/lib/format";
import { seatFigure } from "@/lib/polls";
import { useLang } from "@/lib/i18n/lang";
import POLLS from "@/lib/i18n/polls";
import { pollsterName, Tx } from "./polls/names";

type Props = { polls: Poll[]; parties: Pick<Party, "id" | "name" | "bloc">[]; blocs: { id: string; label: string }[]; config: PollsConfig };
/** A poll's own seat total (whole seats as printed); averaged figures use seatFigure. */
const number = (value: number) => (Math.round(value * 10) / 10).toLocaleString("en-US");
export default function PollSensitivity({ polls, parties, blocs, config }: Props) {
  const lang = useLang(), he = lang === "he", t = POLLS[lang].sens, pn = (name: string) => pollsterName(name, lang);
  const params = useSearchParams(); const router = useRouter(); const query = params.toString();
  const defaults = parties.filter((p) => p.bloc === "net" && polls.some((poll) => poll.results[p.id] || poll.combined.some((group) => group.parties.includes(p.id)))).map((p) => p.id);
  function read() { const q = new URLSearchParams(query); return { fiction:readSyntheticShare(q.get("synthetic")), selected: q.has("with") ? [...new Set((q.get("with") ?? "").split(",").filter((id) => parties.some((p) => p.id === id)))] : defaults, days: [7, 14, 28].includes(Number(q.get("window"))) ? Number(q.get("window")) : config.currentWindowDays, weighting: q.get("weight") === "equal" ? "equal" as Weighting : "sqrt" as Weighting, excluded: [...new Set((q.get("exclude") ?? "").split(",").filter((name) => config.pollsters.includes(name)))] }; }
  const [settings, setSettings] = useState(read); const [shareStatus, setShareStatus] = useState(""); const [shareUrl, setShareUrl] = useState(""); const fiction=settings.fiction;
  // Shared URLs and browser history are external state; form controls remain immediate.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => setSettings(read()), [query]); // eslint-disable-line react-hooks/exhaustive-deps
  const pool = useMemo(() => sensitivityPool(polls, config, settings.days, settings.excluded), [polls, config, settings.days, settings.excluded]);
  const model = useMemo(() => sensitivityAverages(pool.polls, parties.map((p) => p.id), settings.weighting), [pool.polls, parties, settings.weighting]);
  const individual = pool.polls.map((poll) => ({ poll, tally: selectedPollTotal(poll, settings.selected) }));
  const complete = individual.filter((row) => row.tally.complete);
  const values = complete.map((row) => row.tally.total);
  const majority = values.filter((n) => n >= 61).length;
  const selectedRows = model.rows.filter((row) => settings.selected.includes(row.id));
  const knownTotal = Math.round(selectedRows.reduce((sum, row) => sum + (row.normalized ?? 0), 0) * 10) / 10;
  const missingAverage = selectedRows.filter((row) => row.normalized === null);
  const name = (id: string) => parties.find((p) => p.id === id)?.name ?? id;
  const hypothetical = syntheticThresholdSeats(fiction);
  async function share() {
    const q = writeSensitivityView(new URLSearchParams(params),settings);
    const path = `${he ? "/he/polls" : "/polls"}?${q}#sensitivity`; const url = `https://www.israelielection.org${path}`; setShareUrl(url); router.push(path, { scroll: false });
    try { await navigator.clipboard.writeText(url); setShareStatus(t.copied); } catch { setShareStatus(t.copyFailed); }
  }
  return <section id="sensitivity" className="poll-sensitivity" aria-labelledby="sensitivity-h"><h2 id="sensitivity-h" className="sec-h">{t.title}</h2><p>{t.intro}</p>
    <div className="poll-presets">{blocs.map((bloc) => <button type="button" key={bloc.id} onClick={() => setSettings({ ...settings, selected: parties.filter((p) => p.bloc === bloc.id && polls.some((poll) => poll.results[p.id] || poll.combined.some((g) => g.parties.includes(p.id)))).map((p) => p.id) })}>{he ? t.preset(bloc.label) : <>{bloc.label} (reported lists)</>}</button>)}<button type="button" onClick={() => setSettings({ ...settings, selected: [] })}>{t.clearLists}</button></div>
    <fieldset className="poll-selection"><legend>{he ? t.selected(settings.selected.length) : <>Selected lists ({settings.selected.length})</>}</legend><div className="poll-choices">{parties.map((p) => <label key={p.id}><input type="checkbox" checked={settings.selected.includes(p.id)} onChange={() => setSettings({ ...settings, selected: settings.selected.includes(p.id) ? settings.selected.filter((id) => id !== p.id) : [...settings.selected, p.id] })} />{p.name}</label>)}</div></fieldset>
    <div className="poll-controls"><label>{t.window}<select value={settings.days} onChange={(e) => setSettings({ ...settings, days: Number(e.target.value) })}>{[7, 14, 28].map((d) => <option key={d} value={d}>{he ? t.days(d) : <>{d} days</>}</option>)}</select></label><label>{t.weights}<select value={settings.weighting} onChange={(e) => setSettings({ ...settings, weighting: e.target.value as Weighting })}><option value="sqrt">{t.sqrt}</option><option value="equal">{t.equal}</option></select></label><button type="button" onClick={() => setSettings({ ...settings, days: config.currentWindowDays, weighting: "sqrt", excluded: [] })}>{t.restore}</button><button type="button" onClick={share}>{t.copy}</button></div>
    <details><summary>{he ? t.inclusion(settings.excluded.length) : <>Publisher inclusion ({settings.excluded.length} excluded)</>}</summary><p className="note">{t.inclusionNote}</p><div className="poll-choices">{config.pollsters.filter((publisher) => pool.eligible.some((p) => p.pollster === publisher)).map((publisher) => <label key={publisher}><input type="checkbox" checked={!settings.excluded.includes(publisher)} onChange={() => setSettings({ ...settings, excluded: settings.excluded.includes(publisher) ? settings.excluded.filter((p) => p !== publisher) : [...settings.excluded, publisher] })} />{he ? <Tx text={pn(publisher)} lang={lang} /> : publisher}</label>)}</div><button type="button" onClick={() => setSettings({ ...settings, excluded: config.withoutVariant.pollsters })}>{he ? t.useAlt(config.withoutVariant.pollsters.map(pn)) : <>Use the alternative excluding {config.withoutVariant.pollsters.join(" and ")}</>}</button></details>
    <p className="note">{he ? t.anchor(pool.anchor ? mediumDate(pool.anchor, lang) : null, pool.polls.length, settings.days) : <>Publication window anchor: {pool.anchor ? mediumDate(pool.anchor) : "no campaign poll available"}. {pool.polls.length} included polls from {settings.days} days ending at that date. These are not necessarily separate research firms or independent samples.</>}</p>
    <div className="sensitivity-reading" role="status" aria-live="polite">{!settings.selected.length ? <p>{t.selectOne}</p> : !pool.polls.length ? <p>{t.noPolls}</p> : he ? <><p><b>{t.majority(majority, complete.length)}</b>{t.majorityTail(majority)}{values.length > 0 && t.observed(number(Math.min(...values)), number(Math.max(...values)))} {individual.length - complete.length > 0 && t.incomplete(individual.length - complete.length)}</p><p>{t.avgLead(missingAverage.length > 0)}{t.avgMid}<b>{t.avgSeats(seatFigure(knownTotal))}</b>.{missingAverage.length > 0 && t.noSeparate(missingAverage.map((r) => name(r.id)).join(", "))} <Link href="#method">{t.method}</Link>.</p></> : <><p><b>{majority} of {complete.length} complete polls</b> show these lists reaching the 61-seat absolute-majority target.{values.length > 0 && <> Their observed range is {number(Math.min(...values))}–{number(Math.max(...values))} seats.</>} {individual.length - complete.length > 0 && <>{individual.length - complete.length} incomplete polls are excluded from this denominator.</>}</p><p>{missingAverage.length ? "The known subtotal of the" : "The"} normalized coalition average is <b>{seatFigure(knownTotal)} seats</b>.{missingAverage.length > 0 && <> No separate average for {missingAverage.map((r) => name(r.id)).join(", ")}.</>} <Link href="#method">Method</Link>.</p></>}</div>
    {settings.selected.length > 0 && pool.polls.length > 0 && <><div className="table-scroll poll-scroller" tabIndex={0} role="region" aria-label={t.tableAria}><table className="data-table"><thead><tr><th>{t.thPoll}</th><th className="num">{t.thSeats}</th><th>{t.thCoverage}</th></tr></thead><tbody>{individual.map(({ poll, tally }) => <tr key={poll.id}><th scope="row">{mediumDate(poll.published, lang)}<br />{he ? <Tx text={pn(poll.pollster)} lang={lang} /> : poll.pollster}</th><td className="num">{tally.complete ? number(tally.total) : t.subtotal(number(tally.total))}</td><td>{tally.missing.length > 0 ? t.missing(tally.missing.map(name).join(", ")) : t.complete}{tally.combined.length > 0 && t.combinedOnce(tally.combined.map((g) => g.map(name).join(" + ")).join("; "))}{poll.url && <a href={poll.url}>{t.cited}</a>}</td></tr>)}</tbody></table></div>
    <h3 className="sec-h3">{t.depsH}</h3><p className="note">{t.depsNote}</p><div className="table-scroll"><table className="data-table"><thead><tr><th>{t.thList}</th><th>{t.thPasses}</th><th className="num">{t.thMean}</th><th className="num">{t.thNorm}</th><th className="num">{t.thWithout}</th></tr></thead><tbody>{selectedRows.map((row) => <tr key={row.id}><th scope="row">{name(row.id)}</th><td>{row.average ? t.passes(row.average.k, row.average.n, !!row.average.nearThreshold) : t.notReported}</td><td className="num">{row.average ? seatFigure(row.average.avg) : t.unknown}</td><td className="num">{row.normalized === null ? t.unknown : seatFigure(row.normalized)}</td><td className="num">{row.normalized === null ? t.unknown : <>{seatFigure(knownTotal - row.normalized)}{knownTotal >= 61 && knownTotal - row.normalized < 61 && t.loses}</>}</td></tr>)}</tbody></table></div></>}
    <details className="sensitivity-inputs"><summary>{t.inputs}</summary><p className="note">{he ? t.inputsNote(seatFigure(model.rawSum), model.scale) : <>Counted per-list means sum to {seatFigure(model.rawSum)} before normalization. {model.scale < 1 ? `Scale factor ${model.scale.toFixed(4)} reduces that sum to 120 before rounding.` : "No scaling is applied because that sum is at most 120."} Tenths may not sum to exactly 120 after rounding. An average is computed only where a list passes; a list passing in fewer than half its separate reports counts zero in the coalition average.</>}</p><ul>{model.weights.map(({ poll, weight, usedN, imputed }) => <li key={poll.id}>{he ? t.weightRow(mediumDate(poll.published, lang), pn(poll.pollster), poll.n, weight.toFixed(3)) : <>{mediumDate(poll.published)}, {poll.pollster}: n {poll.n ?? "not recorded"}; effective weight {weight.toFixed(3)}</>}{settings.weighting === "equal" ? t.wEqual : imputed ? usedN === null ? t.wNone : t.wMedian(usedN) : t.wSqrt(usedN!)}{poll.url && <>, <a href={poll.url}>{t.source}</a></>}</li>)}</ul></details>
    <details className="synthetic-threshold"><summary>{t.fiction}</summary><p>{t.fictionIntro}</p><label>{he ? t.fictionLabel(fiction.toFixed(1)) : <>Fictional list E: {fiction.toFixed(1)}%</>}<input type="range" min={2.5} max={4.5} step={0.1} value={fiction} onChange={(e) => setSettings({...settings,fiction:Number(e.target.value)})} /></label><p role="status">{he ? t.fictionRead(hypothetical.passed, hypothetical.coalition) : <>E {hypothetical.passed ? "passes" : "fails"} 3.25%. A+B receives {hypothetical.coalition} of 120 seats, {hypothetical.coalition >= 61 ? "reaching" : "below"} the absolute-majority target.</>}</p><p>{he ? t.allocated(Object.entries(hypothetical.seats).map(([id, seats]) => `${id} ${seats}`).join(", ")) : <>Allocated seats: {Object.entries(hypothetical.seats).map(([id, seats]) => `${id} ${seats}`).join(", ")}. A failed list gets no seats; its votes are not transferred. </>}<Link href="/how-it-works/seats" {...(he ? { hrefLang: "en" } : {})}>{t.allocLink}</Link>.</p></details>
    <p role="status">{shareStatus}</p>{shareUrl && <label className="poll-share">{t.viewLink}<input readOnly value={shareUrl} onFocus={(e) => e.currentTarget.select()} /></label>}
  </section>;
}
