"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { selectedPollTotal, sensitivityPool, sensitivityAverages, syntheticThresholdSeats, readSyntheticShare, writeSensitivityView, type Weighting } from "@/lib/sensitivity";
import type { Party, Poll, PollsConfig } from "@/lib/types";

type Props = { polls: Poll[]; parties: Pick<Party, "id" | "name" | "bloc">[]; blocs: { id: string; label: string }[]; config: PollsConfig };
const number = (value: number) => (Math.round(value * 10) / 10).toLocaleString("en-US");
export default function PollSensitivity({ polls, parties, blocs, config }: Props) {
  const params = useSearchParams(); const router = useRouter(); const query = params.toString();
  const defaults = parties.filter((p) => p.bloc === "net" && polls.some((poll) => poll.results[p.id] || poll.combined.some((group) => group.parties.includes(p.id)))).map((p) => p.id);
  function read() { const q = new URLSearchParams(query); return { fiction:readSyntheticShare(q.get("synthetic")), selected: q.has("with") ? [...new Set((q.get("with") ?? "").split(",").filter((id) => parties.some((p) => p.id === id)))] : defaults, days: [7, 14, 28].includes(Number(q.get("window"))) ? Number(q.get("window")) : config.currentWindowDays, weighting: q.get("weight") === "equal" ? "equal" as Weighting : "sqrt" as Weighting, excluded: [...new Set((q.get("exclude") ?? "").split(",").filter((name) => config.pollsters.includes(name)))] }; }
  const [settings, setSettings] = useState(read); const [shareStatus, setShareStatus] = useState(""); const [shareUrl, setShareUrl] = useState(""); const fiction=settings.fiction;
  // Shared URLs and browser history are external state; form controls remain immediate.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => setSettings(read()), [query]); // eslint-disable-line react-hooks/exhaustive-deps
  const pool = useMemo(() => sensitivityPool(polls, config, settings.days, settings.excluded), [polls, config, settings.days, settings.excluded]);
  const model = useMemo(() => sensitivityAverages(pool.polls, parties.map((p) => p.id), settings.weighting), [pool.polls, parties, settings.weighting]);
  const individual = pool.polls.map((poll) => ({ poll, tally: selectedPollTotal(poll, settings.selected) }));
  const complete = individual.filter((row) => row.tally.complete);
  const values = complete.map((row) => row.tally.total);
  const majority = values.filter((n) => n >= 61).length;
  const selectedRows = model.rows.filter((row) => settings.selected.includes(row.id));
  const knownTotal = Math.round(selectedRows.reduce((sum, row) => sum + (row.normalized ?? 0), 0) * 10) / 10;
  const missingAverage = selectedRows.filter((row) => row.normalized === null);
  const name = (id: string) => parties.find((p) => p.id === id)?.name ?? id;
  const hypothetical = syntheticThresholdSeats(fiction);
  async function share() {
    const q = writeSensitivityView(new URLSearchParams(params),settings);
    const path = `/polls?${q}#sensitivity`; const url = `https://www.israelielection.org${path}`; setShareUrl(url); router.push(path, { scroll: false });
    try { await navigator.clipboard.writeText(url); setShareStatus("View link copied, including the selected lists, polling assumptions and fictional threshold setting."); } catch { setShareStatus("Select and copy the view link below."); }
  }
  return <section id="sensitivity" className="poll-sensitivity" aria-labelledby="sensitivity-h"><h2 id="sensitivity-h" className="sec-h">What survives a different polling assumption?</h2><p>Choose lists, compare their total in each current poll, then vary the inclusion and weighting rules. This describes the available polls; it does not estimate a chance of winning or a confidence interval.</p>
    <div className="poll-presets">{blocs.map((bloc) => <button type="button" key={bloc.id} onClick={() => setSettings({ ...settings, selected: parties.filter((p) => p.bloc === bloc.id && polls.some((poll) => poll.results[p.id] || poll.combined.some((g) => g.parties.includes(p.id)))).map((p) => p.id) })}>{bloc.label} (reported lists)</button>)}<button type="button" onClick={() => setSettings({ ...settings, selected: [] })}>Clear lists</button></div>
    <fieldset className="poll-selection"><legend>Selected lists ({settings.selected.length})</legend><div className="poll-choices">{parties.map((p) => <label key={p.id}><input type="checkbox" checked={settings.selected.includes(p.id)} onChange={() => setSettings({ ...settings, selected: settings.selected.includes(p.id) ? settings.selected.filter((id) => id !== p.id) : [...settings.selected, p.id] })} />{p.name}</label>)}</div></fieldset>
    <div className="poll-controls"><label>Window ending at the newest campaign poll<select value={settings.days} onChange={(e) => setSettings({ ...settings, days: Number(e.target.value) })}>{[7, 14, 28].map((d) => <option key={d} value={d}>{d} days</option>)}</select></label><label>Average weights<select value={settings.weighting} onChange={(e) => setSettings({ ...settings, weighting: e.target.value as Weighting })}><option value="sqrt">Square root of sample size (site default)</option><option value="equal">Equal poll weights (alternative)</option></select></label><button type="button" onClick={() => setSettings({ ...settings, days: config.currentWindowDays, weighting: "sqrt", excluded: [] })}>Restore site method</button><button type="button" onClick={share}>Copy this view</button></div>
    <details><summary>Publisher inclusion ({settings.excluded.length} excluded)</summary><p className="note">Include or exclude by a stated methodological choice, not because you dislike the result. One latest eligible campaign poll per publisher is used. Exits are excluded.</p><div className="poll-choices">{config.pollsters.filter((publisher) => pool.eligible.some((p) => p.pollster === publisher)).map((publisher) => <label key={publisher}><input type="checkbox" checked={!settings.excluded.includes(publisher)} onChange={() => setSettings({ ...settings, excluded: settings.excluded.includes(publisher) ? settings.excluded.filter((p) => p !== publisher) : [...settings.excluded, publisher] })} />{publisher}</label>)}</div><button type="button" onClick={() => setSettings({ ...settings, excluded: config.withoutVariant.pollsters })}>Use the alternative excluding {config.withoutVariant.pollsters.join(" and ")}</button></details>
    <p className="note">Publication window anchor: {pool.anchor || "no campaign poll available"}. {pool.polls.length} included polls from {settings.days} days ending at that date. These are not necessarily separate research firms or independent samples.</p>
    <div className="sensitivity-reading" role="status" aria-live="polite">{!settings.selected.length ? <p>Select at least one list.</p> : !pool.polls.length ? <p>No current polls remain under these choices. Restore the site method or include a publisher.</p> : <><p><b>{majority} of {complete.length} complete polls</b> show these lists reaching the 61-seat absolute-majority target.{values.length > 0 && <> Their observed range is {number(Math.min(...values))}–{number(Math.max(...values))} seats.</>} {individual.length - complete.length > 0 && <>{individual.length - complete.length} incomplete polls are excluded from this denominator.</>}</p><p><b>{number(knownTotal)} seats</b> — {missingAverage.length ? "known subtotal of the" : "the"} normalized coalition average.{missingAverage.length > 0 && <> No separate average for {missingAverage.map((r) => name(r.id)).join(", ")}.</>} <Link href="#method">Method</Link>.</p></>}</div>
    {settings.selected.length > 0 && pool.polls.length > 0 && <><div className="table-scroll poll-scroller" tabIndex={0} role="region" aria-label="Selected-list totals in current polls"><table className="data-table"><thead><tr><th>Published / publisher</th><th className="num">Selected-list seats</th><th>Coverage and source</th></tr></thead><tbody>{individual.map(({ poll, tally }) => <tr key={poll.id}><th scope="row">{poll.published}<br />{poll.pollster}</th><td className="num">{tally.complete ? number(tally.total) : `${number(tally.total)} known subtotal`}</td><td>{tally.missing.length > 0 ? `Not separately known: ${tally.missing.map(name).join(", ")}. ` : "Complete. "}{tally.combined.length > 0 && `Combined once: ${tally.combined.map((g) => g.map(name).join(" + ")).join("; ")}. `}{poll.url && <a href={poll.url}>Cited report</a>}</td></tr>)}</tbody></table></div>
    <h3>Threshold and partner dependencies</h3><p className="note">Passing counts describe polls reporting the list separately. “Without” below simply removes this list’s modeled seats while holding the others fixed; it does not redistribute seats or simulate what other voters would do.</p><div className="table-scroll"><table className="data-table"><thead><tr><th>Selected list</th><th>Passes / reported</th><th className="num">Passing-poll mean</th><th className="num">Normalized seats</th><th className="num">Known subtotal without this list</th></tr></thead><tbody>{selectedRows.map((row) => <tr key={row.id}><th scope="row">{name(row.id)}</th><td>{row.average ? `${row.average.k} / ${row.average.n}${row.average.nearThreshold ? " · fewer than half pass" : ""}` : "Not separately reported"}</td><td className="num">{row.average ? number(row.average.avg) : "Unknown"}</td><td className="num">{row.normalized === null ? "Unknown" : number(row.normalized)}</td><td className="num">{row.normalized === null ? "Unknown" : <>{number(knownTotal - row.normalized)}{knownTotal >= 61 && knownTotal - row.normalized < 61 && " · loses 61 target"}</>}</td></tr>)}</tbody></table></div></>}
    <details className="sensitivity-inputs"><summary>Every average input and its effective weight</summary><p className="note">Counted per-list means sum to {number(model.rawSum)} before normalization. {model.scale < 1 ? `Scale factor ${model.scale.toFixed(4)} reduces that sum to 120 before rounding.` : "No scaling is applied because that sum is at most 120."} Tenths may not sum to exactly 120 after rounding. An average is computed only where a list passes; a list passing in fewer than half its separate reports counts zero in the coalition average.</p><ul>{model.weights.map(({ poll, weight, usedN, imputed }) => <li key={poll.id}>{poll.published} · {poll.pollster}: n {poll.n ?? "not recorded"}; effective weight {weight.toFixed(3)}{settings.weighting === "equal" ? " (equal)" : imputed ? usedN === null ? " (no known sample sizes; equal fallback)" : ` (median n ${usedN} imputed)` : ` (√${usedN})`}{poll.url && <> · <a href={poll.url}>source</a></>}</li>)}</ul></details>
    <details className="synthetic-threshold"><summary>A fictional threshold example: watch an arithmetic majority change</summary><p>These are five invented lists and 100,000 hypothetical valid votes. A has 31%, B 19%, C 15%, E the share you choose, and D the remainder (35% minus E). The selected group is A+B. No surplus agreements are assumed. Nothing here is inferred from an Israeli seat poll or predicts voters.</p><label>Fictional list E: {fiction.toFixed(1)}%<input type="range" min={2.5} max={4.5} step={0.1} value={fiction} onChange={(e) => setSettings({...settings,fiction:Number(e.target.value)})} /></label><p role="status">E {hypothetical.passed ? "passes" : "fails"} 3.25%. A+B receives {hypothetical.coalition} of 120 seats, {hypothetical.coalition >= 61 ? "reaching" : "below"} the absolute-majority target.</p><p>Allocated seats: {Object.entries(hypothetical.seats).map(([id, seats]) => `${id} ${seats}`).join(", ")}. A failed list gets no seats; its votes are not transferred. <Link href="/how-it-works/seats">Read the allocation method</Link>.</p></details>
    <p role="status">{shareStatus}</p>{shareUrl && <label className="poll-share">View link<input readOnly value={shareUrl} onFocus={(e) => e.currentTarget.select()} /></label>}
  </section>;
}
