"use client";
import {useLayoutEffect,useRef,useState} from "react";
import {partyColor,PARTY_COLOR_NOTE} from "@/lib/party-colors";
import type {TrendPanel} from "./PollTrends";
import {alignTrend,lineSegments,nearestDateIndex,seatTicks} from "@/lib/poll-chart";
import {fmt,mediumDate,shortDate} from "@/lib/format";
const DAY=86400_000,PAD={l:38,r:20,t:22,b:34};
const DASHES=["","9 4","2 4","12 4 2 4","5 3","14 6"];
const value=(n:number)=>fmt(Math.round(n*10)/10);
export default function PollComparison({panels,dates,from,to,yMax}:{panels:TrendPanel[];dates:string[];from:string;to:string;yMax:number}){
 const ref=useRef<HTMLDivElement>(null);const [w,setW]=useState(0);const [index,setIndex]=useState(dates.length-1);const [hidden,setHidden]=useState<string[]>([]);const [active,setActive]=useState<string|null>(null);const [pinned,setPinned]=useState<string|null>(null);const highlighted=active??pinned;
 useLayoutEffect(()=>{const el=ref.current;if(!el)return;const ro=new ResizeObserver(()=>setW(el.clientWidth));ro.observe(el);return()=>ro.disconnect();},[]);
 const H=w<600?360:440;const t0=Date.parse(from),t1=Date.parse(to);const x=(date:string)=>PAD.l+(Date.parse(date)-t0)/Math.max(DAY,t1-t0)*(w-PAD.l-PAD.r);const y=(n:number)=>PAD.t+(1-n/yMax)*(H-PAD.t-PAD.b);
 const series=panels.map((p)=>{const slot=panels.filter((other)=>other.bloc===p.bloc).findIndex((other)=>other.id===p.id);return {...p,points:alignTrend(p.trend,dates),dash:DASHES[slot%DASHES.length],color:partyColor(p.id)};});
 const visible=series.filter((p)=>!hidden.includes(p.id));const selectedDate=dates[Math.min(index,dates.length-1)];const focus=visible.find((p)=>p.id===highlighted);const focusedPoint=focus?.points[index];
 function inspect(clientX:number,clientY?:number){const rect=ref.current?.getBoundingClientRect();if(!rect)return;const px=clientX-rect.left;const at=nearestDateIndex(dates,t0+(px-PAD.l)/Math.max(1,w-PAD.l-PAD.r)*(t1-t0));setIndex(at);if(clientY!==undefined){const py=clientY-rect.top;const known=visible.filter((p)=>p.points[at]?.avg!==null);known.sort((a,b)=>Math.abs(y(a.points[at].avg!)-py)-Math.abs(y(b.points[at].avg!)-py));setActive(known[0]?.id??null);}}
 const read=focus?`${focus.name}: ${focusedPoint?.avg===null||!focusedPoint?"no separate average available":`${value(focusedPoint.avg)} seats from ${focusedPoint.n} separately reporting polls`}`:`${visible.length} parties shown`;
 return <section className="pc" aria-labelledby="pc-title"><h2 id="pc-title" className="sec-h">Compare every party over time</h2><p className="note">All {panels.length} separately tracked lists are shown initially on the same <b>0–{yMax} seat scale</b>. These lines show each list’s <b>passing-poll mean</b>, before coalition normalization; they need not add to 120. Missing separate averages break the line. No smoothing or uncertainty band is added.</p>
 <p id="pc-instructions" className="pc-instructions">Point or tap the graph to inspect a date and highlight the nearest line. Focus a party name in the legend to trace it; checkboxes show or hide lines. On the graph, left/right changes date and up/down changes highlighted party. The date slider also works by keyboard and touch.</p>
 <div className="pc-plot" ref={ref}>{w>0&&<svg width={w} height={H} role="img" tabIndex={0} aria-label={`Running passing-poll means for ${visible.length} parties, shared zero-based seat scale`} aria-describedby="pc-instructions pc-reading" onPointerMove={(e)=>inspect(e.clientX,e.clientY)} onPointerDown={(e)=>inspect(e.clientX,e.clientY)} onPointerLeave={()=>setActive(null)} onKeyDown={(e)=>{if(e.key==="ArrowLeft"||e.key==="ArrowRight"){e.preventDefault();setIndex((i)=>Math.max(0,Math.min(dates.length-1,i+(e.key==="ArrowRight"?1:-1))));}if(e.key==="Home"||e.key==="End"){e.preventDefault();setIndex(e.key==="Home"?0:dates.length-1);}if(e.key==="ArrowUp"||e.key==="ArrowDown"){e.preventDefault();const at=visible.findIndex((p)=>p.id===highlighted);setPinned(visible[at<0 ? e.key==="ArrowDown"?0:visible.length-1 : (at+(e.key==="ArrowDown"?1:-1)+visible.length)%visible.length]?.id??null);setActive(null);}}}>
 {seatTicks(0,yMax).map((n)=><g key={n}><line x1={PAD.l} x2={w-PAD.r} y1={y(n)} y2={y(n)} className="pt-grid"/><text x={PAD.l-8} y={y(n)} textAnchor="end" dominantBaseline="middle" className="pc-tick">{n}</text></g>)}<text x={PAD.l} y={12} className="pc-tick">Seats, passing-poll mean</text>
 <text x={PAD.l} y={H-10} className="pc-tick">{shortDate(from)}</text><text x={w-PAD.r} y={H-10} className="pc-tick" textAnchor="end">{shortDate(to)}</text>
 {selectedDate&&<line x1={x(selectedDate)} x2={x(selectedDate)} y1={PAD.t} y2={H-PAD.b} className="pt-cross"/>}
 {[...visible].sort((a,b)=>Number(a.id===highlighted)-Number(b.id===highlighted)).map((p)=><g key={p.id} opacity={highlighted&&highlighted!==p.id?0.22:1}>{lineSegments(p.points).map((segment,i)=><g key={i}><path d={segment.map((point,j)=>`${j?"L":"M"}${x(point.date).toFixed(1)},${y(point.avg!).toFixed(1)}`).join("")} fill="none" stroke={p.color} strokeWidth={p.id===highlighted?3.5:2} strokeDasharray={p.dash} strokeLinejoin="round"/>{segment.length===1&&<circle cx={x(segment[0].date)} cy={y(segment[0].avg!)} r={3} fill={p.color}/>}</g>)}{p.points[index]?.avg!==null&&p.points[index]&&<circle cx={x(selectedDate)} cy={y(p.points[index].avg!)} r={p.id===highlighted?5:3} fill={p.color} stroke="var(--sheet)" strokeWidth={1.5}/>}</g>)}
 {focus&&focusedPoint?.avg!==null&&focusedPoint&&<g><rect x={Math.max(PAD.l,Math.min(w-170,x(selectedDate)-145))} y={Math.max(PAD.t,y(focusedPoint.avg!)-28)} width={146} height={22} fill="var(--sheet)"/><text x={Math.max(PAD.l+5,Math.min(w-165,x(selectedDate)-140))} y={Math.max(PAD.t+15,y(focusedPoint.avg!)-13)} className="pc-label">{focus.short??focus.name}, {value(focusedPoint.avg!)} seats</text></g>}
 </svg>}</div>
 <div className="pc-date"><label htmlFor="pc-date">Publication date: <b>{mediumDate(selectedDate)}</b></label><input id="pc-date" type="range" min={0} max={Math.max(0,dates.length-1)} step={1} value={index} aria-valuetext={mediumDate(selectedDate)} onChange={(e)=>setIndex(Number(e.target.value))}/></div>
 <p id="pc-reading" className="pc-reading" role="status" aria-live="polite">{mediumDate(selectedDate)}, {read}.</p>
 <div className="pc-toolbar"><button type="button" onClick={()=>{setHidden([]);setActive(null);setPinned(null);}}>Show all parties</button><button type="button" onClick={()=>{setActive(null);setPinned(null);}}>Clear highlight</button>{!visible.length&&<span>No lines selected; choose a party or show all.</span>}</div>
 <ul className="pc-legend">{series.map((p)=><li key={p.id} className={highlighted===p.id?"active":undefined}><input type="checkbox" aria-label={`Show ${p.name}`} checked={!hidden.includes(p.id)} onChange={()=>{setHidden((old)=>old.includes(p.id)?old.filter((id)=>id!==p.id):[...old,p.id]);if(active===p.id)setActive(null);if(pinned===p.id)setPinned(null);}}/><button type="button" disabled={hidden.includes(p.id)} onPointerEnter={()=>setActive(p.id)} onPointerLeave={()=>setActive(null)} onFocus={()=>{setPinned(p.id);setActive(null);}} onBlur={()=>setActive(null)} onClick={()=>{setPinned(p.id);setActive(null);}} aria-pressed={pinned===p.id} aria-label={`Highlight ${p.name}`}><svg width="26" height="12" aria-hidden="true"><line x1="1" x2="25" y1="6" y2="6" stroke={p.color} strokeWidth="2.5" strokeDasharray={p.dash}/></svg><span>{p.name}</span></button><span className="pc-value">{p.points[index]?.avg===null||!p.points[index]?"n/a":value(p.points[index].avg!)}</span></li>)}</ul><p className="fig-src">Legend values are passing-poll means on the selected date; n/a means no separate average. Each list has its own shade; related shades mark editorial political families. Dashes and name labels also distinguish lists. Zero means no seats in any separately reporting poll in that pool, not a seat equivalent of the vote threshold.</p>
 <p className="fig-src">{PARTY_COLOR_NOTE}</p>
 <details className="pc-data"><summary>Accessible data table: every chart date and party</summary><div className="table-scroll" tabIndex={0} role="region" aria-label="All-party running average data, horizontally scrollable"><table className="data-table"><caption>Passing-poll mean seats before normalization; no separate average is not zero.</caption><thead><tr><th>Date</th>{series.map((p)=><th key={p.id}>{p.name}</th>)}</tr></thead><tbody>{dates.map((date,i)=><tr key={date}><th scope="row">{date}</th>{series.map((p)=><td key={p.id}>{p.points[i].avg===null?"Not available":value(p.points[i].avg!)}</td>)}</tr>)}</tbody></table></div></details>
 </section>;
}
