import { describe,it,expect } from "vitest";
import { buildExport } from "./export-data";
import { exportCsv } from "./export";
import { averagePoll,parties } from "./data";
import { historicalElections } from "./votemap-data";
describe("sourced exports match selected views",()=>{
 it("preserves selected issue answers and publication/check evidence",async()=>{const model=await buildExport("issue",new URLSearchParams("issue=courts-appointments&p=likud,yashar"));expect(model?.rows).toHaveLength(2);expect(model?.rows.map((r)=>r[2])).toEqual(parties.filter((p)=>["likud","yashar"].includes(p.id)).map((p)=>p.name));expect(model?.rows.some((r)=>String(r[5]).includes("2025"))).toBe(true);expect(model?.sources.length).toBeGreaterThan(0);});
 it("preserves cabinet/support/abstention and actual current normalized seats",async()=>{const model=await buildExport("coalition",new URLSearchParams("poll=avg&with=likud&support=shas&abstain=jl"));expect(model?.rows.find((r)=>r[0]===parties.find((p)=>p.id==="shas")!.name)).toEqual([parties.find((p)=>p.id==="shas")!.name,"Outside support",averagePoll.results.shas.seats]);expect(model?.rows.find((r)=>r[0]===parties.find((p)=>p.id==="jl")!.name)?.[1]).toBe("Hypothetical abstention");expect(model?.assumptions.some((s)=>s.includes("square-root"))).toBe(true);expect(model?.assumptions.some((s)=>s.includes("real MKs cast whole votes"))).toBe(true);});
 it("carries a basis column and marks unstated rows",async()=>{const model=(await buildExport("issue",new URLSearchParams("issue=relig&p=likud,otzma")))!;expect(model.headers[3+1]).toBe("Basis");const likud=model.rows.filter((r)=>r[2]==="Likud").map((r)=>r[4]);expect(likud).toContain("Not said publicly (unstated)");const unstated=model.rows.find((r)=>r[4]==="Not said publicly (unstated)")!;expect(String(unstated[3]).startsWith("Not said publicly: ")).toBe(true);});
 it("keeps locality original list values/denominators and missing-state validation",async()=>{const model=await buildExport("locality",new URLSearchParams("election=2022&list=Likud&locality=4000"));const e=historicalElections[4];const original=e.rows.find((r)=>r[0]===4000)!;const index=e.lists.findIndex((l)=>l.name==="Likud");const row=model!.rows.find((r)=>r[0]===e.label&&r[1]==="Likud")!;expect(row[3]).toBe(original[4+index]);expect(row[4]).toBe((original[4+index]/original[3]*100).toFixed(2));expect(model!.asOf).toContain("2022-11-01");expect(model!.asOf).toContain("source files fetched");const other=model!.rows.find((r)=>r[0]===e.label&&r[1]==="Other lists")!;expect(other[4]).toBe((Number(other[3])/original[3]*100).toFixed(2));expect(await buildExport("locality",new URLSearchParams("locality=9999"))).toBeNull();});
 it("retains the selected historical map mode in the return link and human-readable assumptions",async()=>{const model=await buildExport("locality",new URLSearchParams("election=2022&list=Likud&locality=4000&mode=leader"));expect(model?.view).toContain("mode=leader");expect(model?.assumptions[0]).toContain("leading list");});
 it("CSV retains sources, quotes multiline answers and blocks formula execution",async()=>{const model=(await buildExport("issue",new URLSearchParams("issue=courts-appointments&p=likud,yashar")))!;model.rows.push(["=HYPERLINK(bad)",'quote " and\nline',null]);const csv=exportCsv(model);expect(csv).toContain('"\'=HYPERLINK(bad)"');expect(csv).toContain('quote "" and\nline');expect(csv).toContain("CC BY-NC 4.0");expect(csv).toContain(model.sources[0].url);});
});
